import { randomUUID } from "node:crypto";
import type { Request } from "express";
import { Router } from "express";
import { ZodError } from "zod";
import { createStaticIphoneArAsset } from "../services/arAssetService";
import {
  designConfigSchema,
  type DesignConfig,
} from "../schemas/designConfig";

/**
 * AR routes.
 *
 * Current purpose:
 * - receive validated pool design config
 * - create a server-hosted USDZ preview asset
 * - return iPhone Quick Look preview information
 *
 * Future purpose:
 * - generate GLB/USDZ dynamically from design config
 * - cache generated USDZ files
 * - return final generated USDZ URL
 */
export const arRouter = Router();

arRouter.post("/iphone-preview", async (request, response) => {
  try {
    const config = designConfigSchema.parse(request.body);

    const publicOrigin = getPublicOriginFromRequest(request);
    const iphonePreview = await buildIphonePreview(config, publicOrigin);

    response.json({
      data: iphonePreview,
      error: null,
      meta: {
        timestamp: new Date().toISOString(),
      },
    });
  } catch (error) {
    if (error instanceof ZodError) {
      response.status(400).json({
        data: null,
        error: {
          code: "AR_DESIGN_VALIDATION_FAILED",
          message: "Design config is invalid for iPhone AR preview.",
          details: error.issues.map((issue) => ({
            path: issue.path.join("."),
            message: issue.message,
          })),
        },
        meta: {
          timestamp: new Date().toISOString(),
        },
      });

      return;
    }

    response.status(500).json({
      data: null,
      error: {
        code: "IPHONE_AR_PREVIEW_FAILED",
        message: "Could not create iPhone AR preview.",
      },
      meta: {
        timestamp: new Date().toISOString(),
      },
    });
  }
});

/**
 * Builds iPhone AR preview response.
 *
 * Step 16 behavior:
 * - creates a backend-hosted USDZ file by copying the static template
 * - returns the backend USDZ URL
 *
 * Later this function will call the real USDZ generator/converter pipeline.
 */
async function buildIphonePreview(config: DesignConfig, publicOrigin: string) {
  const previewId = randomUUID();

  const generatedAsset = await createStaticIphoneArAsset({
    previewId,
    config,
  });

  const generatedUsdzUrl = `${publicOrigin}${generatedAsset.relativeUrl}`;

  return {
    previewId,

    mode: "server-static-usdz-fallback",

    config,

    quickLook: {
      platform: "ios",
      fileFormat: "usdz",
      href: generatedUsdzUrl,
      rel: "ar",
      status: "ready-with-server-static-fallback",
    },

    pipeline: {
      dynamicGeneration: "pending",
      currentStep:
        "Backend-generated AR asset hosting is ready. Next step is real USDZ generation.",
      futureOutputPath: generatedAsset.relativeUrl,
    },

    notes: [
      "This endpoint validates the current live pool design.",
      "The current USDZ file is generated by copying a static server template.",
      "Dynamic USDZ generation will replace this template copy later.",
    ],
  };
}

/**
 * Resolves the public origin for generated asset URLs.
 *
 * Local:
 * http://localhost:4000
 *
 * Railway:
 * https://<railway-domain>
 */
function getPublicOriginFromRequest(request: Request) {
  const forwardedProto = request.get("x-forwarded-proto");
  const forwardedHost = request.get("x-forwarded-host");

  const protocol = forwardedProto?.split(",")[0]?.trim() ?? request.protocol;
  const host = forwardedHost?.split(",")[0]?.trim() ?? request.get("host");

  if (!host) {
    throw new Error("Could not resolve request host for public AR URL.");
  }

  return `${protocol}://${host}`;
}
